# Generated by Django 3.0.5 on 2021-04-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_id', models.IntegerField()),
                ('Cust_name', models.CharField(max_length=100)),
                ('Cust_type', models.CharField(max_length=3)),
            ],
        ),
    ]
