# Generated by Django 3.0.5 on 2021-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDoperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Cust_type',
            field=models.CharField(max_length=30),
        ),
    ]
